### ISSUE TITLE
Dúvida sobre o andamento do curso

### ISSUE THREAD

**Issue by danimlds** [MichelliBrito/curso-html-css-bootstrap#1]
Olá! :smiley:

Gostaria de saber quando será disponibilizada das próximas aulas?

Muito obrigado por sempre estar compartilhando conhecimento.

**Comment by MichelliBrito** [comment]
Olá bom dia!

Toda terça feira irei disponibilizar uma nova aula e serão 7 aulas ao todo
:)

Em ter., 19 de jan. de 2021 16:19, Daniel Moura <notifications@github.com>
escreveu:

**Comment by danimlds** [comment]
Obrigado! 👍
